### ISSUE TITLE
Age variables produce errors

### ISSUE THREAD

**Issue by andkov** [dss-hmi/nypd-ccrb-2020-shiny#3]
@mmmmtoasty19 , when selecting `mos_age_incident` and `complainant_age_incident` the graph results in error

**Comment by mmmmtoasty19** [comment]
@andkov  I have removed them as choices.  The function is supposed to only work for categorical and these were discrete variables.   

If there is another approach I am open to suggestions

**Comment by andkov** [comment]
@mmmmtoasty19 , good call, I missed that fact
